### ISSUE TITLE
Tracking issue for Asset Mining and Staking migration

### ISSUE THREAD

**Issue by liuchengxu** [chainx-org/ChainX#138]
#### Staking

- [ ] Integrate `session` module of Substrate.
  - [x] Initial work #137
  - [ ] Test

- [ ] Slashing.
  - [x] Integrate `imonline` module, regular slashing components. #140
  - [ ] Test
     - [ ] Force new era when the reward pot of some slashed validator is empty.

- [x] Integrate treasury module. Tracked at #147.
  - [x] The treasury account id is required for distributing the shares of treasury per session reward. #146

- [x] Claim the staking reward for nominators.
  - [x] `claim` Call
  - [x] Test

#### Asset Mining

- [x] Integrate into Staking. #144
- [ ] Claim the reward for asset miners.
  - [x] `claim` Call.
  - [x] `claim` limit, e.g., the minimal Staking requirement, etc. #144 
  - [x] Issue deposit reward. #146
  - [x] 10% mining dividend for referral. #168
  - [ ] Test

#### RPC

- [x] Staking #152
- [ ] Asset Mining, docs for #179
- [ ] Spot, docs for https://github.com/chainx-org/ChainX/pull/178

#### Audit

- [ ] overflow
- [ ] divided by zero
- [ ] RPC safety

The unchecked items in this issue will be continued in #297 and tracked in the following testnets.
