### ISSUE TITLE
Transaction weight

### ISSUE THREAD

**Issue by liuchengxu** [chainx-org/ChainX#145]
Apply the transaction weight based on ChainX 1.0 and substrate weights system:

- [x] xpallet_assets_registrar #205
- [x] xpallet_dex_spot #205
- [x] xpallet_mining_asset #205
- [x] xpallet_mining_staking #205 

Continued in #283.
