### ISSUE TITLE
Improve gateway

### ISSUE THREAD

**Issue by koushiro** [chainx-org/ChainX#305]
- [ ] improve `gateway bitcoin`
   - [x] add xp-gateway-bitcoin #347 #354 #355
   - [x] header #385 #398
   - [x] tx #352 #357
   - [x] mock and test #350
   - [x] benchmarking #361
   - [ ] trustee
- [ ] improve `gateway common`
   - [x] mock and benchmarking #366
   - [ ] pallet
- [x] improve `gateway records`
~~- [ ] integrate `gateway common` and `gateway records` into a single pallet called `gateway trustee`~~
