### ISSUE TITLE
Tracking issue for Substrate 3.0 upgrade

### ISSUE THREAD

**Issue by liuchengxu** [chainx-org/ChainX#522]
## ChainX 3.0.0

- [x] Wait for https://github.com/chainx-org/ChainX/pull/439, continues in the [develop branch](https://github.com/chainx-org/ChainX/tree/develop).
- [x] Rework the `transaction-fee` xpallet(#442)
- [x] Force the validators in the waiting list to run a node(#546)
- [x] Fix the Docker build(#545)
- [ ] Since [https://github.com/paritytech/substrate/pull/7474](https://github.com/paritytech/substrate/pull/7474/files#diff-79991d75ead2aa9757d97be3307d93100616d08c554e4c97e6567e6c8c625f1dR558), if the global logger has been initialized before the init of substrate cli, the binary will exit directly.  We need to work it out.
- [ ] Rerun benchmarks(#565)
- [ ] Take care of the pallets that need a storage migration
- [ ] Bump up the version

## Attribute macro migration

- [x] Migrate all the xpallets to the attribute macro.
    - [x] xpallet-support @alannotnerd
    - [x] xpallet-genesis-builder(#552) @alannotnerd
    - [x] xpallet-assets-registrar(#550) @VegeBun-csj
    - [x] xpallet-transaction-fee @rain-9811
    - [x] xpallet-system (#553) @alannotnerd
    - [x] xpallet-assets (#560) @rjman-ljm
    - [x] xpallet-mining-asset @liuchengxu
    - [x] xpallet-mining-staking(#551) @liuchengxu
    - [x] xpallet-gateway-bitcoin(#532) @alannotnerd
    - [x] xpallet-gateway-records(#555) @hacpy
    - [x] xpallet-gateway-common(#562) @Han-sx
    - [x] xpallet-dex-spot (#559) @hacpy 

The other notable changes:

- https://github.com/paritytech/polkadot-sdk/issues/337
- Handle the result properly https://github.com/chainx-org/ChainX/pull/439/files#diff-a00140ac73428f3646031b22fd61e8f625d4eed905f2a295e891504f5e23cea9R513
- Although `multicurrency` is currently unused, we need to have a closer look with care. https://github.com/chainx-org/ChainX/pull/439/files#diff-92e26c66a540c66a3a6ca16e898559219dcd6ab8d06e2eb61822f2f35796c59eR405
