### ISSUE TITLE
Tracking issue for chainx-bridge pallet

### ISSUE THREAD

**Issue by alannotnerd** [chainx-org/ChainX#529]
## Bridging multiple chains
- [ ] Identity vault from various chains.
- [ ] Identity collateral from various chains.
- [ ] Identity requests from various chains.
- [ ] Identity asset from various chains.
